import numpy as np
import pandas as pd
from datetime import datetime


# generaterandomnamessimilartodocker(lazy_sloth)
def gen_name(num_concats=1, seed=None):
    rng = np.random.default_rng(seed) if seed else np.random.default_rng()
    random_int = rng.integers(low=0, high=len(nouns))
    word = nouns[random_int]
    for i in range(num_concats):
        random_int = rng.integers(low=0, high=len(adjectives))
        word = adjectives[random_int] + '_' + word
    return word

nouns = ['time', 'way', 'year', 'work', 'government', 'day', 'man', 'men', 'world', 'life', 'lives', 'part', 'house',
         'houses',
         'course', 'case', 'system', 'place', 'end', 'group', 'company', 'companies', 'party', 'parties', 'information',
         'informations', 'school', 'fact', 'money', 'moneys', 'point', 'example', 'state', 'business', 'businesses',
         'night', 'area', 'areas', 'water', 'thing', 'family', 'families', 'head', 'hand', 'order', 'john', 'side',
         'home', 'development', 'week', 'power', 'country', 'countries', 'council', 'use', 'service', 'room', 'market',
         'problem', 'problems', 'court', 'lot', 'a', 'aes', 'war', 'police', 'interest', 'interests', 'car', 'law',
         'laws', 'road', 'form', 'face', 'education', 'policy', 'policies', 'research', 'researches', 'sort', 'office',
         'body', 'bodies', 'person', 'persons', 'health', 'healths', 'mother', 'question', 'period', 'name', 'book',
         'level', 'child', 'children', 'control', 'society', 'societies', 'minister', 'view', 'door', 'line',
         'community', 'communities', 'south', 'city', 'cities', 'god', 'father', 'centre', 'centres', 'effect', 'staff',
         'staffs', 'position', 'kind', 'job', 'woman', 'women', 'action', 'management', 'managements', 'act', 'process',
         'processes', 'north', 'age', 'evidence', 'evidences', 'idea', 'ideas', 'west', 'support', 'moment', 'sense',
         'report', 'mind', 'church', 'churches', 'morning', 'death', 'change', 'industry', 'industries', 'land', 'care',
         'century', 'centuries', 'range', 'table', 'back', 'trade', 'history', 'histories', 'study', 'studies',
         'street', 'committee', 'rate', 'word', 'food', 'foods', 'language', 'experience', 'result', 'team', 'other',
         'sir', 'sirs', 'section', 'programme', 'air', 'authority', 'authorities', 'role', 'reason', 'price', 'town',
         'class', 'classes', 'nature', 'subject', 'department', 'union', 'bank', 'member', 'value', 'need', 'east',
         'practice', 'practices', 'type', 'paper', 'date', 'decision', 'figure', 'right', 'wife', 'wives', 'president',
         'university', 'universities', 'friend', 'club', 'quality', 'qualities', 'voice', 'lord', 'stage', 'king', 'us',
         'situation', 'light', 'tax', 'taxes', 'production', 'march', 'marches', 'secretary', 'secretaries', 'art',
         'board', 'may', 'hospital', 'month', 'music', 'musics', 'cost', 'field', 'award', 'issue', 'bed', 'project',
         'chapter', 'girl', 'game', 'amount', 'basis', 'bases', 'knowledge', 'knowledges', 'approach', 'approaches',
         'series', 'series', 'love', 'top', 'news', 'front', 'future', 'manager', 'account', 'computer', 'security',
         'securities', 'rest', 'labour', 'structure', 'hair', 'bill', 'heart', 'force', 'attention', 'movement',
         'success', 'successes', 'letter', 'agreement', 'capital', 'analysis', 'analyses', 'population', 'environment',
         'performance', 'model', 'material', 'theory', 'theories', 'growth', 'fire', 'chance', 'boy', 'relationship',
         'son', 'sea', 'record', 'size', 'property', 'properties', 'space', 'term', 'director', 'plan', 'behaviour',
         'behaviours', 'treatment', 'energy', 'energies', 'st', 'peter', 'income', 'cup', 'scheme', 'design',
         'response', 'association', 'choice', 'pressure', 'hall', 'couple', 'technology', 'technologies', 'defence',
         'list', 'chairman', 'chairmen', 'loss', 'losses', 'activity', 'activities', 'contract', 'county', 'counties',
         'wall', 'paul', 'difference', 'army', 'armies', 'hotel', 'sun', 'product', 'summer', 'set', 'village',
         'colour', 'colours', 'floor', 'season', 'unit', 'park', 'hour', 'investment', 'test', 'garden', 'husband',
         'employment', 'style', 'science', 'look', 'deal', 'charge', 'help', 'helps', 'economy', 'economies', 'new',
         'page', 'risk', 'advice', 'event', 'picture', 'commission', 'fish', 'fish', 'college', 'oil', 'doctor',
         'opportunity', 'opportunities', 'film', 'conference', 'operation', 'application', 'press', 'presses', 'extent',
         'addition', 'station', 'window', 'shop', 'access', 'accesses', 'region', 'doubt', 'majority', 'majorities',
         'degree', 'television', 'blood', 'statement', 'sound', 'election', 'parliament', 'site', 'mark', 'importance',
         'title', 'species', 'species', 'increase', 'return', 'concern', 'public', 'publics', 'competition', 'software',
         'glass', 'glasses', 'lady', 'ladies', 'answer', 'earth', 'daughter', 'daughters', 'purpose', 'responsibility',
         'responsibilities', 'leader', 'river', 'eye', 'eyes', 'ability', 'abilities', 'appeal', 'opposition',
         'campaign', 'respect', 'task', 'instance', 'sale', 'whole', 'officer', 'method', 'division', 'source', 'piece',
         'pattern', 'lack', 'disease', 'equipment', 'equipments', 'surface', 'oxford', 'demand', 'post', 'mouth',
         'radio', 'provision', 'attempt', 'sector', 'firm', 'status', 'statuses', 'peace', 'peaces', 'variety',
         'varieties', 'teacher', 'show', 'shows', 'speaker', 'baby', 'babies', 'arm', 'base', 'miss', 'misses',
         'safety', 'safeties', 'trouble', 'culture', 'direction', 'context', 'character', 'characters', 'box', 'boxes',
         'discussion', 'past', 'weight', 'organisation', 'organisations', 'start', 'brother', 'brothers', 'league',
         'condition', 'machine', 'argument', 'sex', 'sexes', 'budget', 'english', 'transport', 'share', 'mum', 'cash',
         'cashes', 'principle', 'exchange', 'aid', 'library', 'libraries', 'version', 'rule', 'tea', 'balance',
         'afternoon', 'reference', 'protection', 'truth', 'truths', 'district', 'turn', 'smith', 'review', 'minute',
         'duty', 'duties', 'survey', 'presence', 'influence', 'stone', 'stones', 'dog', 'benefit', 'collection',
         'executive', 'speech', 'speeches', 'function', 'queen', 'marriage', 'stock', 'failure', 'kitchen', 'student',
         'effort', 'holiday', 'career', 'attack', 'length', 'horse', 'progress', 'progresses', 'plant', 'visit',
         'relation', 'ball', 'memory', 'memories', 'bar', 'opinion', 'quarter', 'impact', 'scale', 'race', 'image',
         'trust', 'justice', 'edge', 'gas', 'gases', 'railway', 'expression', 'advantage', 'gold', 'wood', 'network',
         'text', 'forest', 'sister', 'chair', 'cause', 'foot', 'feet', 'rise', 'half', 'halves', 'winter', 'corner',
         'insurance', 'insurances', 'step', 'damage', 'credit', 'credits', 'pain', 'possibility', 'possibilities',
         'legislation', 'legislations', 'strength', 'speed', 'crime', 'hill', 'debate', 'will', 'supply', 'supplies',
         'present', 'confidence', 'mary', 'patient', 'wind', 'solution', 'band', 'museum', 'museums', 'farm', 'pound',
         'henry', 'henries', 'match', 'matches', 'assessment', 'message', 'football', 'no', 'noes', 'animal', 'skin',
         'scene', 'article', 'stuff', 'stuffs', 'introduction', 'play', 'administration', 'administrations', 'fear',
         'dad', 'proportion', 'island', 'contact', 'japan', 'claim', 'kingdom', 'video', 'videos', 'tv', 'tvs',
         'existence', 'telephone', 'move', 'traffic', 'distance', 'relief', 'cabinet', 'unemployment', 'reality',
         'realities', 'target', 'trial', 'rock', 'concept', 'spirit', 'accident', 'organization', 'construction',
         'coffee', 'phone', 'distribution', 'train', 'sight', 'difficulty', 'difficulties', 'factor', 'exercise',
         'weekend', 'battle', 'prison', 'grant', 'aircraft', 'aircraft', 'tree', 'trees', 'bridge', 'strategy',
         'strategies', 'contrast', 'communication', 'background', 'shape', 'wine', 'star', 'hope', 'selection',
         'detail', 'user', 'path', 'client', 'search', 'searches', 'master', 'rain', 'rains', 'offer', 'goal', 'dinner',
         'freedom', 'attitude', 'while', 'agency', 'agencies', 'seat', 'manner', 'favour', 'fig.', 'fig.', 'pair',
         'pairs', 'crisis', 'crises', 'smile', 'prince', 'danger', 'call', 'capacity', 'capacities', 'output', 'note',
         'procedure', 'theatre', 'tour', 'recognition', 'recognitions', 'middle', 'absence', 'absences', 'sentence',
         'package', 'track', 'card', 'sign', 'commitment', 'player', 'threat', 'weather', 'element', 'conflict',
         'notice', 'victory', 'victories', 'bottom', 'finance', 'fund', 'violence', 'file', 'profit', 'standard',
         'jack', 'route', 'china', 'expenditure', 'expenditures', 'second', 'discipline', 'cell', 'pp.', 'reaction',
         'castle', 'congress', 'congresses', 'individual', 'lead', 'consideration', 'debt', 'option', 'payment',
         'exhibition', 'reform', 'emphasis', 'emphases', 'spring', 'audience', 'feature', 'touch', 'touches', 'estate',
         'assembly', 'assemblies', 'volume', 'youth', 'contribution', 'curriculum', 'curricula', 'appearance', 'martin',
         'tom', 'boat', 'institute', 'membership', 'branch', 'branches', 'bus', 'buses', 'waste', 'heat', 'neck',
         'object', 'captain', 'driver', 'challenge', 'conversation', 'occasion', 'code', 'crown', 'birth', 'silence',
         'silences', 'literature', 'literatures', 'faith', 'hell', 'entry', 'entries', 'transfer', 'gentleman',
         'gentlemen', 'bag', 'coal', 'investigation', 'leg', 'belief', 'total', 'major', 'document', 'description',
         'murder', 'aim', 'manchester', 'flight', 'conclusion', 'drug', 'tradition', 'pleasure', 'connection', 'owner',
         'treaty', 'treaties', 'tony', 'tonies', 'alan', 'desire', 'desires', 'professor', 'copy', 'copies', 'ministry',
         'ministries', 'acid', 'palace', 'address', 'addresses', 'institution', 'lunch', 'lunches', 'generation',
         'partner', 'engine', 'newspaper', 'cross', 'crosses', 'reduction', 'welfare', 'welfares', 'definition', 'key',
         'release', 'vote', 'examination', 'judge', 'atmosphere', 'leadership', 'sky', 'skies', 'breath', 'creation',
         'row', 'guide', 'milk', 'cover', 'screen', 'intention', 'criticism', 'jones', 'joneses', 'silver', 'customer',
         'journey', 'explanation', 'green', 'measure', 'brain', 'significance', 'phase', 'injury', 'injuries', 'run',
         'coast', 'technique', 'valley', 'drink', 'magazine', 'potential', 'drive', 'revolution', 'bishop',
         'settlement', 'christ', 'christs', 'metal', 'motion', 'index', 'indexes', 'adult', 'inflation', 'sport',
         'surprise', 'pension', 'factory', 'factories', 'tape', 'flow', 'iron', 'trip', 'lane', 'pool', 'independence',
         'hole', 'un', 'flat', 'content', 'pay', 'noise', 'combination', 'session', 'appointment', 'fashion',
         'consumer', 'accommodation', 'temperature', 'mike', 'religion', 'author', 'nation', 'northern', 'sample',
         'assistance', 'assistances', 'interpretation', 'aspect', 'display', 'displays', 'shoulder', 'agent', 'gallery',
         'galleries', 'republic', 'cancer', 'proposal', 'sequence', 'simon', 'ship', 'interview', 'vehicle',
         'democracy', 'democracies', 'improvement', 'involvement', 'involvements', 'general', 'enterprise', 'van',
         'meal', 'breakfast', 'motor', 'channel', 'impression', 'tone', 'sheet', 'pollution', 'bob', 'beauty',
         'beauties', 'square', 'vision', 'spot', 'distinction', 'brown', 'crowd', 'fuel', 'desk', 'sum', 'decline',
         'revenue', 'fall', 'diet', 'bedroom', 'soil', 'reader', 'shock', 'fruit', 'behalf', 'behalves', 'deputy',
         'deputies', 'roof', 'roofs', 'nose', 'steel', 'co', 'artist', 'graham', 'plate', 'song', 'maintenance',
         'maintenances', 'formation', 'grass', 'grasses', 'spokesman', 'spokesmen', 'ice', 'talk', 'program', 'link',
         'ring', 'expert', 'establishment', 'plastic', 'candidate', 'rail', 'passage', 'joe', 'parish', 'parishes',
         'ref', 'emergency', 'emergencies', 'liability', 'liabilities', 'identity', 'identities', 'location',
         'framework', 'strike', 'countryside', 'map', 'lake', 'household', 'approval', 'border', 'bottle', 'bird',
         'constitution', 'autumn', 'cat', 'agriculture', 'concentration', 'concentrations', 'guy', 'dress', 'dresses',
         'victim', 'mountain', 'editor', 'theme', 'error', 'loan', 'stress', 'stresses', 'recovery', 'recoveries',
         'electricity', 'electricities', 'recession', 'wealth', 'wealths', 'request', 'comparison', 'lewis', 'lewises',
         'white', 'walk', 'focus', 'foci', 'chief', 'parent', 'sleep', 'mass', 'masses', 'jane', 'bush', 'bushes',
         'foundation', 'bath', 'item', 'lifespan', 'lee', 'lees', 'publication', 'decade', 'beach', 'beaches', 'sugar',
         'height', 'charity', 'charities', 'writer', 'panel', 'struggle', 'dream', 'outcome', 'efficiency',
         'efficiencies', 'offence', 'offences', 'resolution', 'reputation', 'specialist', 'taylor', 'taylors', 'pub',
         'co-operation', 'port', 'incident', 'representation', 'bread', 'chain', 'initiative', 'clause', 'resistance',
         'mistake', 'worker', 'advance', 'empire', 'notion', 'mirror', 'delivery', 'deliveries', 'chest', 'licence',
         'licences', 'frank', 'average', 'awareness', 'awarenesses', 'travel', 'expansion', 'block', 'alternative',
         'chancellor', 'meat', 'store', 'self', 'selves', 'break', 'drama', 'dramas', 'corporation', 'currency',
         'currencies', 'extension', 'convention', 'partnership', 'skill', 'furniture', 'furnitures', 'round', 'regime',
         'inquiry', 'inquiries', 'rugby', 'rugbies', 'philosophy', 'philosophies', 'scope', 'gate', 'minority',
         'minorities', 'intelligence', 'restaurant', 'consequence', 'mill', 'golf', 'retirement', 'priority',
         'priorities', 'plane', 'gun', 'gap', 'core', 'uncle', 'thatcher', 'fun', 'arrival', 'snow', 'no.', 'nos.',
         'command', 'abuse', 'limit', 'championship']
adjectives = ['abandoned', 'abdominal', 'abhorrent', 'abiding', 'abject', 'able', 'able-bodied', 'abnormal',
              'abounding', 'abrasive', 'abrupt', 'absent', 'absentminded', 'absolute', 'absorbed', 'absorbing',
              'abstracted', 'absurd', 'abundant', 'abusive', 'abysmal', 'academic', 'acceptable', 'accepting',
              'accessible', 'accidental', 'acclaimed', 'accommodating', 'accompanying', 'accountable', 'accurate',
              'accusative', 'accused', 'accusing', 'acerbic', 'achievable', 'aching', 'acid', 'acidic', 'acknowledged',
              'acoustic', 'acrid', 'acrimonious', 'acrobatic', 'actionable', 'active', 'actual', 'ad', 'adamant',
              'adaptable', 'adaptive', 'addicted', 'addictive', 'additional', 'adept', 'adequate', 'adhesive',
              'adjacent', 'adjoining', 'adjustable', 'administrative', 'admirable', 'admired', 'admiring', 'adopted',
              'adoptive', 'adorable', 'adored', 'adoring', 'adrenalized', 'adroit', 'adult', 'advanced', 'advantageous',
              'adventurous', 'adversarial', 'advisable', 'aerial', 'affable', 'affected', 'affectionate', 'affirmative',
              'affordable', 'afraid', 'afternoon', 'ageless', 'aggravated', 'aggravating', 'aggressive', 'agitated',
              'agonizing', 'agrarian', 'agreeable', 'aimless', 'airline', 'airsick', 'ajar', 'alarmed', 'alarming',
              'alert', 'algebraic', 'alien', 'alienated', 'alike', 'alive', 'all', 'all-around', 'alleged', 'allowable',
              'all-purpose', 'all-too-common', 'alluring', 'allusive', 'alone', 'aloof', 'alterable', 'alternating',
              'alternative', 'amazed', 'amazing', 'ambiguous', 'ambitious', 'ambulant', 'ambulatory', 'amiable',
              'amicable', 'amphibian', 'amused', 'amusing', 'an', 'ancient', 'anecdotal', 'anemic', 'angelic',
              'angered', 'angry', 'angular', 'animal', 'animated', 'annoyed', 'annoying', 'annual', 'anonymous',
              'another', 'antagonistic', 'anticipated', 'anticlimactic', 'anticorrosive', 'antiquated', 'antiseptic',
              'antisocial', 'antsy', 'anxious', 'any', 'apathetic', 'apologetic', 'apologizing', 'appalling',
              'appealing', 'appetizing', 'applauding', 'applicable', 'applicative', 'appreciative', 'apprehensive',
              'approachable', 'approaching', 'appropriate', 'approving', 'approximate', 'aquatic', 'architectural',
              'ardent', 'arduous', 'arguable', 'argumentative', 'arid', 'aristocratic', 'aromatic', 'arresting',
              'arrogant', 'artful', 'artificial', 'artistic', 'artless', 'ashamed', 'aspiring', 'assertive',
              'assignable', 'assorted', 'assumable', 'assured', 'assuring', 'astonished', 'astonishing', 'astounded',
              'astounding', 'astringent', 'astronomical', 'astute', 'asymmetrical', 'athletic', 'atomic', 'atrocious',
              'attachable', 'attainable', 'attentive', 'attractive', 'attributable', 'atypical', 'audacious',
              'auspicious', 'authentic', 'authoritarian', 'authoritative', 'autobiographic', 'autographed', 'automatic',
              'autonomous', 'available', 'avant-garde', 'avenging', 'average', 'avian', 'avid', 'avoidable', 'awake',
              'awakening', 'aware', 'away', 'awesome', 'awful', 'awkward', 'axiomatic', 'babbling', 'baby',
              'background', 'backhanded', 'bacterial', 'bad', 'bad-tempered', 'baffled', 'baffling', 'bald', 'balding',
              'balmy', 'bandaged', 'banging', 'bankable', 'banned', 'bantering', 'barbaric', 'barbarous', 'barbequed',
              'barefooted', 'barking', 'barren', 'bashful', 'basic', 'battered', 'batty', 'bawling', 'beady', 'beaming',
              'bearable', 'beautiful', 'beckoning', 'bedazzled', 'bedazzling', 'beefy', 'beeping', 'befitting',
              'befuddled', 'beginning', 'belching', 'believable', 'bellicose', 'belligerent', 'bellowing', 'bendable',
              'beneficial', 'benevolent', 'benign', 'bent', 'berserk', 'best', 'betrayed', 'better', 'better',
              'better-late-than-never', 'bewildered', 'bewildering', 'bewitched', 'bewitching', 'biased', 'biblical',
              'big', 'big-city', 'bigger', 'biggest', 'big-headed', 'bighearted', 'bigoted', 'bilingual', 'billable',
              'billowy', 'binary', 'binding', 'bioactive', 'biodegradable', 'biographical', 'bite-sized', 'biting',
              'bitter', 'bizarre', 'black', 'black-and-blue', 'blamable', 'blameless', 'bland', 'blank', 'blaring',
              'blasphemous', 'blatant', 'blazing', 'bleached', 'bleak', 'bleary', 'bleary-eyed', 'blessed', 'blind',
              'blindfolded', 'blinding', 'blissful', 'blistering', 'bloated', 'blonde', 'bloodied', 'blood-red',
              'bloodthirsty', 'bloody', 'blooming', 'blossoming', 'blue', 'blundering', 'blunt', 'blurred', 'blurry',
              'blushing', 'boastful', 'bodacious', 'bohemian', 'boiling', 'boisterous', 'bold', 'bookish', 'booming',
              'boorish', 'bordering', 'bored', 'boring', 'born', 'bossy', 'both', 'bothered', 'bouncing', 'bouncy',
              'boundless', 'bountiful', 'boyish', 'braided', 'brainless', 'brainy', 'brash', 'brassy', 'brave',
              'brawny', 'brazen', 'breakable', 'breathable', 'breathless', 'breathtaking', 'breezy', 'bribable',
              'brick', 'brief', 'bright', 'bright-eyed', 'bright-red', 'brilliant', 'briny', 'brisk', 'bristly',
              'broad', 'broken', 'broken-hearted', 'bronchial', 'bronze', 'bronzed', 'brooding', 'brown', 'bruised',
              'brunette', 'brutal', 'brutish', 'bubbly', 'budget', 'built-in', 'bulky', 'bumpy', 'bungling', 'buoyant',
              'bureaucratic', 'burly', 'burnable', 'burning', 'bushy', 'busiest', 'business', 'bustling', 'busy',
              'buzzing', 'cackling', 'caged', 'cagey', 'calculable', 'calculated', 'calculating', 'callous', 'calm',
              'calming', 'camouflaged', 'cancelled', 'cancerous', 'candid', 'cantankerous', 'capable', 'capricious',
              'captivated', 'captivating', 'captive', 'carefree', 'careful', 'careless', 'caring', 'carnivorous',
              'carpeted', 'carsick', 'casual', 'catastrophic', 'catatonic', 'catchable', 'caustic', 'cautious',
              'cavalier', 'cavernous', 'ceaseless', 'celebrated', 'celestial', 'centered', 'central', 'cerebral',
              'ceremonial', 'certain', 'certifiable', 'certified', 'challenged', 'challenging', 'chance', 'changeable',
              'changing', 'chanting', 'charging', 'charismatic', 'charitable', 'charmed', 'charming', 'chattering',
              'chatting', 'chatty', 'chauvinistic', 'cheap', 'cheapest', 'cheeky', 'cheerful', 'cheering', 'cheerless',
              'cheery', 'chemical', 'chewable', 'chewy', 'chic', 'chicken', 'chief', 'childish', 'childlike',
              'chilling', 'chilly', 'chivalrous', 'choice', 'choking', 'choppy', 'chronological', 'chubby', 'chuckling',
              'chunky', 'cinematic', 'circling', 'circular', 'circumstantial', 'civil', 'civilian', 'civilized',
              'clammy', 'clamoring', 'clandestine', 'clanging', 'clapping', 'clashing', 'classic', 'classical',
              'classifiable', 'classified', 'classy', 'clean', 'cleanable', 'clear', 'cleared', 'clearheaded', 'clever',
              'climatic', 'climbable', 'clinging', 'clingy', 'clinical', 'cliquish', 'clogged', 'cloistered', 'close',
              'closeable', 'closed', 'close-minded', 'cloudless', 'cloudy', 'clownish', 'clueless', 'clumsy',
              'cluttered', 'coachable', 'coarse', 'cockamamie', 'cocky', 'codified', 'coercive', 'cognitive',
              'coherent', 'cohesive', 'coincidental', 'cold', 'coldhearted', 'collaborative', 'collapsed', 'collapsing',
              'collectable', 'collegial', 'colloquial', 'colonial', 'colorful', 'colorless', 'colossal', 'combative',
              'combined', 'comfortable', 'comforted', 'comforting', 'comical', 'commanding', 'commemorative',
              'commendable', 'commercial', 'committed', 'common', 'communal', 'communicable', 'communicative',
              'communist', 'compact', 'comparable', 'comparative', 'compassionate', 'compelling', 'competent',
              'competitive', 'complacent', 'complaining', 'complete', 'completed', 'complex', 'compliant',
              'complicated', 'complimentary', 'compound', 'comprehensive', 'compulsive', 'compulsory', 'computer',
              'computerized', 'concealable', 'concealed', 'conceited', 'conceivable', 'concerned', 'concerning',
              'concerted', 'concise', 'concurrent', 'condemned', 'condensed', 'condescending', 'conditional',
              'confident', 'confidential', 'confirmable', 'confirmed', 'conflicted', 'conflicting', 'conformable',
              'confounded', 'confused', 'confusing', 'congenial', 'congested', 'congressional', 'congruent',
              'congruous', 'connectable', 'connected', 'connecting', 'connective', 'conscientious', 'conscious',
              'consecutive', 'consensual', 'consenting', 'conservative', 'considerable', 'considerate', 'consistent',
              'consoling', 'conspicuous', 'conspiratorial', 'constant', 'constitutional', 'constrictive',
              'constructive', 'consumable', 'consummate', 'contagious', 'containable', 'contemplative', 'contemporary',
              'contemptible', 'contemptuous', 'content', 'contented', 'contentious', 'contextual', 'continual',
              'continuing', 'continuous', 'contoured', 'contractual', 'contradicting', 'contradictory', 'contrarian',
              'contrary', 'contributive', 'contrite', 'controllable', 'controlling', 'controversial', 'convenient',
              'conventional', 'conversational', 'convinced', 'convincing', 'convoluted', 'convulsive', 'cooing',
              'cooked', 'cool', 'coolest', 'cooperative', 'coordinated', 'copious', 'coquettish', 'cordial', 'corner',
              'cornered', 'corny', 'corporate', 'corpulent', 'correct', 'correctable', 'corrective', 'corresponding',
              'corrosive', 'corrupt', 'corrupting', 'corruptive', 'cosmetic', 'cosmic', 'costly', 'cottony', 'coughing',
              'courageous', 'courteous', 'covert', 'coveted', 'cowardly', 'cowering', 'coy', 'cozy', 'crabby',
              'cracked', 'crackling', 'crafty', 'craggy', 'crammed', 'cramped', 'cranky', 'crashing', 'crass', 'craven',
              'crawling', 'crazy', 'creaking', 'creaky', 'creamy', 'creative', 'credible', 'creeping', 'creepy',
              'crestfallen', 'criminal', 'crippled', 'crippling', 'crisp', 'crispy', 'critical', 'crooked', 'cropped',
              'cross', 'crossed', 'crotchety', 'crowded', 'crucial', 'crude', 'cruel', 'crumbling', 'crumbly',
              'crumply', 'crunchable', 'crunching', 'crunchy', 'crushable', 'crushed', 'crusty', 'crying', 'cryptic',
              'crystalline', 'crystallized', 'cuddly', 'culpable', 'cultural', 'cultured', 'cumbersome', 'cumulative',
              'cunning', 'curable', 'curative', 'curious', 'curly', 'current', 'cursed', 'curt', 'curved', 'curvy',
              'customary', 'cut', 'cute', 'cutting', 'cylindrical', 'cynical', 'daffy', 'daft', 'daily', 'dainty',
              'damaged', 'damaging', 'damp', 'danceable', 'dandy', 'dangerous', 'dapper', 'daring', 'dark', 'darkened',
              'dashing', 'daughterly', 'daunting', 'dawdling', 'day', 'dazed', 'dazzling', 'dead', 'deadly', 'deadpan',
              'deaf', 'deafening', 'dear', 'debatable', 'debonair', 'decadent', 'decayed', 'decaying', 'deceitful',
              'deceivable', 'deceiving', 'decent', 'decentralized', 'deceptive', 'decimated', 'decipherable',
              'decisive', 'declining', 'decorative', 'decorous', 'decreasing', 'decrepit', 'dedicated', 'deep',
              'deepening', 'defeated', 'defective', 'defendable', 'defenseless', 'defensible', 'defensive', 'defiant',
              'deficient', 'definable', 'definitive', 'deformed', 'degenerative', 'degraded', 'dehydrated', 'dejected',
              'delectable', 'deliberate', 'deliberative', 'delicate', 'delicious', 'delighted', 'delightful',
              'delinquent', 'delirious', 'deliverable', 'deluded', 'demanding', 'demented', 'democratic', 'demonic',
              'demonstrative', 'demure', 'deniable', 'dense', 'dependable', 'dependent', 'deplorable', 'deploring',
              'depraved', 'depressed', 'depressing', 'depressive', 'deprived', 'deranged', 'derivative', 'derogative',
              'derogatory', 'descriptive', 'deserted', 'designer', 'desirable', 'desirous', 'desolate', 'despairing',
              'desperate', 'despicable', 'despised', 'despondent', 'destroyed', 'destructive', 'detachable', 'detached',
              'detailed', 'detectable', 'determined', 'detestable', 'detrimental', 'devastated', 'devastating',
              'devious', 'devoted', 'devout', 'dexterous', 'diabolical', 'diagonal', 'didactic', 'different',
              'difficult', 'diffuse', 'digestive', 'digital', 'dignified', 'digressive', 'dilapidated', 'diligent',
              'dim', 'diminishing', 'diminutive', 'dingy', 'diplomatic', 'dire', 'direct', 'direful', 'dirty',
              'disabled', 'disadvantaged', 'disadvantageous', 'disaffected', 'disagreeable', 'disappearing',
              'disappointed', 'disappointing', 'disapproving', 'disarming', 'disastrous', 'discarded', 'discernable',
              'disciplined', 'disconnected', 'discontented', 'discordant', 'discouraged', 'discouraging',
              'discourteous', 'discredited', 'discreet', 'discriminating', 'discriminatory', 'discussable',
              'disdainful', 'diseased', 'disenchanted', 'disgraceful', 'disgruntled', 'disgusted', 'disgusting',
              'disheartened', 'disheartening', 'dishonest', 'dishonorable', 'disillusioned', 'disinclined',
              'disingenuous', 'disinterested', 'disjointed', 'dislikeable', 'disliked', 'disloyal', 'dismal',
              'dismissive', 'disobedient', 'disorderly', 'disorganized', 'disparaging', 'disparate', 'dispassionate',
              'dispensable', 'displaced', 'displeased', 'displeasing', 'disposable', 'disproportionate', 'disproved',
              'disputable', 'disputatious', 'disputed', 'disreputable', 'disrespectful', 'disruptive', 'dissatisfied',
              'dissimilar', 'dissolvable', 'dissolving', 'dissonant', 'dissuasive', 'distant', 'distasteful',
              'distinct', 'distinctive', 'distinguished', 'distracted', 'distracting', 'distraught', 'distressed',
              'distressing', 'distrustful', 'disturbed', 'disturbing', 'divergent', 'diverging', 'diverse',
              'diversified', 'divided', 'divine', 'divisive', 'dizzy', 'dizzying', 'doable', 'documentary', 'dogged',
              'doggish', 'dogmatic', 'doleful', 'dollish', 'domed', 'domestic', 'dominant', 'domineering', 'dorsal',
              'doting', 'double', 'doubtful', 'doubting', 'dovish', 'dowdy', 'down', 'down-and-out', 'downhearted',
              'downloadable', 'downtown', 'downward', 'dozing', 'drab', 'drained', 'dramatic', 'drastic', 'dreaded',
              'dreadful', 'dreaming', 'dreamy', 'dreary', 'drenched', 'dress', 'dressy', 'dried', 'dripping',
              'drivable', 'driven', 'droll', 'drooping', 'droopy', 'drowsy', 'drunk', 'dry', 'dual', 'dubious', 'due',
              'dulcet', 'dull', 'duplicitous', 'durable', 'dusty', 'dutiful', 'dwarfish', 'dwindling', 'dynamic',
              'dysfunctional', 'each', 'eager', 'early', 'earnest', 'ear-piercing', 'ear-splitting', 'earthshaking',
              'earthy', 'east', 'eastern', 'easy', 'eatable', 'eccentric', 'echoing', 'ecological', 'economic',
              'economical', 'economy', 'ecstatic', 'edgy', 'editable', 'educated', 'educational', 'eerie', 'effective',
              'effervescent', 'efficacious', 'efficient', 'effortless', 'effusive', 'egalitarian', 'egocentric',
              'egomaniacal', 'egotistical', 'eight', 'eighth', 'either', 'elaborate', 'elastic', 'elated', 'elderly',
              'electric', 'electrical', 'electrifying', 'electronic', 'elegant', 'elementary', 'elevated', 'elfish',
              'eligible', 'elite', 'eloquent', 'elusive', 'emaciated', 'embarrassed', 'embarrassing', 'embattled',
              'embittered', 'emblematic', 'emboldened', 'embroiled', 'emergency', 'eminent', 'emotional', 'emotionless',
              'empirical', 'empty', 'enamored', 'enchanted', 'enchanting', 'encouraged', 'encouraging', 'encrusted',
              'endangered', 'endearing', 'endemic', 'endless', 'endurable', 'enduring', 'energetic', 'energizing',
              'enforceable', 'engaging', 'engrossing', 'enhanced', 'enigmatic', 'enjoyable', 'enlarged', 'enlightened',
              'enormous', 'enough', 'enraged', 'ensuing', 'enterprising', 'entertained', 'entertaining', 'enthralled',
              'enthused', 'enthusiastic', 'enticing', 'entire', 'entranced', 'entrepreneurial', 'enumerable',
              'enviable', 'envious', 'environmental', 'episodic', 'equable', 'equal', 'equidistant', 'equitable',
              'equivalent', 'erasable', 'erect', 'eroding', 'errant', 'erratic', 'erroneous', 'eruptive', 'escalating',
              'esoteric', 'essential', 'established', 'estimated', 'estranged', 'eternal', 'ethereal', 'ethical',
              'ethnic', 'euphemistic', 'euphoric', 'evasive', 'even', 'evenhanded', 'evening', 'eventful', 'eventual',
              'everlasting', 'every', 'evil', 'evocative', 'exacerbating', 'exact', 'exacting', 'exaggerated',
              'exalted', 'exasperated', 'exasperating', 'excellent', 'exceptional', 'excessive', 'exchangeable',
              'excitable', 'excited', 'exciting', 'exclusive', 'excruciating', 'excusable', 'executable', 'exemplary',
              'exhausted', 'exhausting', 'exhaustive', 'exhilarated', 'exhilarating', 'existing', 'exotic',
              'expandable', 'expanded', 'expanding', 'expansive', 'expectant', 'expected', 'expedient', 'expeditious',
              'expendable', 'expensive', 'experimental', 'expert', 'expired', 'expiring', 'explainable', 'explicit',
              'exploding', 'exploitative', 'exploited', 'explosive', 'exponential', 'exposed', 'express',
              'expressionistic', 'expressionless', 'expressive', 'exquisite', 'extemporaneous', 'extendable',
              'extended', 'extension', 'extensive', 'exterior', 'external', 'extra', 'extra-large', 'extraneous',
              'extraordinary', 'extra-small', 'extravagant', 'extreme', 'exuberant', 'eye-popping', 'fabled',
              'fabulous', 'facetious', 'facial', 'factitious', 'factual', 'faded', 'fading', 'failed', 'faint',
              'fainthearted', 'fair', 'faithful', 'faithless', 'fallacious', 'false', 'falsified', 'faltering',
              'familiar', 'famished', 'famous', 'fanatical', 'fanciful', 'fancy', 'fantastic', 'far', 'faraway',
              'farcical', 'far-flung', 'farsighted', 'fascinated', 'fascinating', 'fascistic', 'fashionable', 'fast',
              'fastest', 'fastidious', 'fast-moving', 'fat', 'fatal', 'fateful', 'fatherly', 'fathomable', 'fathomless',
              'fatigued', 'faulty', 'favorable', 'favorite', 'fawning', 'feared', 'fearful', 'fearless', 'fearsome',
              'feathered', 'feathery', 'feckless', 'federal', 'feeble', 'feebleminded', 'feeling', 'feigned',
              'felonious', 'female', 'feminine', 'fermented', 'ferocious', 'fertile', 'fervent', 'fervid', 'festive',
              'fetching', 'fetid', 'feudal', 'feverish', 'few', 'fewer', 'fictional', 'fictitious', 'fidgeting',
              'fidgety', 'fiendish', 'fierce', 'fiery', 'fifth', 'filmy', 'filtered', 'filthy', 'final', 'financial',
              'fine', 'finicky', 'finite', 'fireproof', 'firm', 'first', 'fiscal', 'fishy', 'fit', 'fitted', 'fitting',
              'five', 'fixable', 'fixed', 'flabby', 'flagrant', 'flaky', 'flamboyant', 'flaming', 'flammable', 'flashy',
              'flat', 'flattened', 'flattered', 'flattering', 'flavored', 'flavorful', 'flavorless', 'flawed',
              'flawless', 'fleeting', 'flexible', 'flickering', 'flimsy', 'flippant', 'flirtatious', 'floating',
              'flooded', 'floppy', 'floral', 'flowering', 'flowery', 'fluent', 'fluffy', 'flushed', 'fluttering',
              'flying', 'foamy', 'focused', 'foggy', 'folded', 'following', 'fond', 'foolhardy', 'foolish',
              'forbidding', 'forceful', 'foreboding', 'foregoing', 'foreign', 'forensic', 'foreseeable', 'forged',
              'forgetful', 'forgettable', 'forgivable', 'forgiving', 'forgotten', 'forked', 'formal', 'formative',
              'former', 'formidable', 'formless', 'formulaic', 'forthright', 'fortuitous', 'fortunate', 'forward',
              'foul', 'foul-smelling', 'four', 'fourth', 'foxy', 'fractional', 'fractious', 'fragile', 'fragmented',
              'fragrant', 'frail', 'frank', 'frantic', 'fraternal', 'fraudulent', 'frayed', 'freakish', 'freaky',
              'freckled', 'free', 'freezing', 'frequent', 'fresh', 'fretful', 'fried', 'friendly', 'frightened',
              'frightening', 'frightful', 'frigid', 'frilly', 'frisky', 'frivolous', 'front', 'frosty', 'frothy',
              'frowning', 'frozen', 'frugal', 'fruitful', 'fruitless', 'fruity', 'frumpy', 'frustrated', 'frustrating',
              'fulfilled', 'fulfilling', 'full', 'fully-grown', 'fumbling', 'fuming', 'fun', 'functional',
              'fundamental', 'fun-loving', 'funniest', 'funny', 'furious', 'furry', 'furthest', 'furtive', 'fussy',
              'futile', 'future', 'futuristic', 'fuzzy', 'gabby', 'gainful', 'gallant', 'galling', 'game', 'gangly',
              'gaping', 'garbled', 'gargantuan', 'garish', 'garrulous', 'gaseous', 'gasping', 'gaudy', 'gaunt', 'gauzy',
              'gawky', 'general', 'generative', 'generic', 'generous', 'genial', 'gentle', 'genuine', 'geographic',
              'geologic', 'geometric', 'geriatric', 'ghastly', 'ghostly', 'ghoulish', 'giant', 'giddy', 'gifted',
              'gigantic', 'giggling', 'gilded', 'giving', 'glad', 'glamorous', 'glaring', 'glass', 'glassy', 'gleaming',
              'glib', 'glistening', 'glittering', 'global', 'globular', 'gloomy', 'glorious', 'glossy', 'glowing',
              'gluey', 'glum', 'gluttonous', 'gnarly', 'gold', 'golden', 'good', 'good-looking', 'good-natured',
              'gooey', 'goofy', 'gorgeous', 'graceful', 'gracious', 'gradual', 'grainy', 'grand', 'grandiose',
              'graphic', 'grateful', 'gratified', 'gratifying', 'grating', 'gratis', 'gratuitous', 'gray', 'greasy',
              'great', 'greatest', 'greedy', 'green', 'gregarious', 'grey', 'grieving', 'grim', 'grimacing', 'grimy',
              'grinding', 'grinning', 'gripping', 'gritty', 'grizzled', 'groaning', 'groggy', 'groomed', 'groovy',
              'gross', 'grotesque', 'grouchy', 'growling', 'grown-up', 'grubby', 'grueling', 'gruesome', 'gruff',
              'grumbling', 'grumpy', 'guaranteed', 'guarded', 'guiltless', 'guilt-ridden', 'guilty', 'gullible',
              'gurgling', 'gushing', 'gushy', 'gusty', 'gutsy', 'habitable', 'habitual', 'haggard', 'hairless', 'hairy',
              'half', 'halfhearted', 'hallowed', 'halting', 'handsome', 'handy', 'hanging', 'haphazard', 'hapless',
              'happy', 'hard', 'hard-to-find', 'hardworking', 'hardy', 'harebrained', 'harmful', 'harmless', 'harmonic',
              'harmonious', 'harried', 'harsh', 'hasty', 'hated', 'hateful', 'haughty', 'haunting', 'hawkish',
              'hazardous', 'hazy', 'head', 'heady', 'healthy', 'heartbreaking', 'heartbroken', 'heartless',
              'heartrending', 'hearty', 'heated', 'heavenly', 'heavy', 'hectic', 'hefty', 'heinous', 'helpful',
              'helpless', 'her', 'heroic', 'hesitant', 'hideous', 'high', 'highest', 'highfalutin', 'high-functioning',
              'high-maintenance', 'high-pitched', 'high-risk', 'hilarious', 'his', 'hissing', 'historical', 'hoarse',
              'hoggish', 'holiday', 'holistic', 'hollow', 'home', 'homeless', 'homely', 'homeopathic', 'homey',
              'homogeneous', 'honest', 'honking', 'honorable', 'hopeful', 'hopeless', 'horizontal', 'hormonal',
              'horned', 'horrendous', 'horrible', 'horrid', 'horrific', 'horrified', 'horrifying', 'hospitable',
              'hostile', 'hot', 'hot', 'hot-blooded', 'hotheaded', 'hot-shot', 'hot-tempered', 'hour-long', 'house',
              'howling', 'huffy', 'huge', 'huggable', 'hulking', 'human', 'humanitarian', 'humanlike', 'humble',
              'humdrum', 'humid', 'humiliated', 'humiliating', 'humming', 'humongous', 'humorless', 'humorous',
              'hungry', 'hurried', 'hurt', 'hurtful', 'hushed', 'husky', 'hydraulic', 'hydrothermal', 'hygienic',
              'hyper-active', 'hyperbolic', 'hypercritical', 'hyperirritable', 'hypersensitive', 'hypertensive',
              'hypnotic', 'hypnotizable', 'hypothetical', 'hysterical', 'icky', 'iconoclastic', 'icy', 'icy-cold',
              'ideal', 'idealistic', 'identical', 'identifiable', 'idiosyncratic', 'idiotic', 'idyllic', 'ignorable',
              'ignorant', 'ill', 'illegal', 'illegible', 'illegitimate', 'ill-equipped', 'ill-fated', 'ill-humored',
              'illicit', 'ill-informed', 'illiterate', 'illogical', 'illuminating', 'illusive', 'illustrious',
              'imaginable', 'imaginary', 'imaginative', 'imitative', 'immaculate', 'immanent', 'immature',
              'immeasurable', 'immediate', 'immense', 'immensurable', 'imminent', 'immobile', 'immodest', 'immoral',
              'immortal', 'immovable', 'impartial', 'impassable', 'impassioned', 'impatient', 'impeccable',
              'impenetrable', 'imperative', 'imperceptible', 'imperceptive', 'imperfect', 'imperial', 'imperialistic',
              'impermeable', 'impersonal', 'impertinent', 'impervious', 'impetuous', 'impish', 'implausible',
              'implicit', 'implosive', 'impolite', 'imponderable', 'important', 'imported', 'imposing', 'impossible',
              'impoverished', 'impractical', 'imprecise', 'impressionable', 'impressive', 'improbable', 'improper',
              'improvable', 'improved', 'improving', 'imprudent', 'impulsive', 'impure', 'inaccessible', 'inaccurate',
              'inactive', 'inadequate', 'inadmissible', 'inadvertent', 'inadvisable', 'inalienable', 'inalterable',
              'inane', 'inanimate', 'inapplicable', 'inappropriate', 'inapt', 'inarguable', 'inarticulate',
              'inartistic', 'inattentive', 'inaudible', 'inauspicious', 'incalculable', 'incandescent', 'incapable',
              'incessant', 'incidental', 'inclusive', 'incoherent', 'incomparable', 'incompatible', 'incompetent',
              'incomplete', 'incomprehensible', 'inconceivable', 'inconclusive', 'incongruent', 'incongruous',
              'inconsequential', 'inconsiderable', 'inconsiderate', 'inconsistent', 'inconsolable', 'inconspicuous',
              'incontrovertible', 'inconvenient', 'incorrect', 'incorrigible', 'incorruptible', 'increasing',
              'incredible', 'incredulous', 'incremental', 'incurable', 'indecent', 'indecipherable', 'indecisive',
              'indefensible', 'indefinable', 'indefinite', 'indelible', 'independent', 'indescribable',
              'indestructible', 'indeterminable', 'indeterminate', 'indicative', 'indifferent', 'indigenous',
              'indignant', 'indirect', 'indiscreet', 'indiscriminate', 'indispensable', 'indisputable', 'indistinct',
              'individual', 'individualistic', 'indivisible', 'indomitable', 'inductive', 'indulgent', 'industrial',
              'industrious', 'ineffective', 'ineffectual', 'inefficient', 'inelegant', 'ineloquent', 'inequitable',
              'inert', 'inescapable', 'inevitable', 'inexact', 'inexcusable', 'inexhaustible', 'inexpedient',
              'inexpensive', 'inexplicable', 'inexpressible', 'inexpressive', 'inextricable', 'infallible', 'infamous',
              'infantile', 'infatuated', 'infected', 'infectious', 'inferable', 'inferior', 'infernal', 'infinite',
              'infinitesimal', 'inflamed', 'inflammable', 'inflammatory', 'inflatable', 'inflated', 'inflexible',
              'influential', 'informal', 'informative', 'informed', 'infrequent', 'infuriated', 'infuriating',
              'ingenious', 'ingenuous', 'inglorious', 'ingratiating', 'inhabitable', 'inharmonious', 'inherent',
              'inhibited', 'inhospitable', 'inhuman', 'inhumane', 'initial', 'injudicious', 'injured', 'injurious',
              'innate', 'inner', 'innocent', 'innocuous', 'innovative', 'innumerable', 'inoffensive', 'inoperable',
              'inoperative', 'inopportune', 'inordinate', 'inorganic', 'inquiring', 'inquisitive', 'insane',
              'insatiable', 'inscrutable', 'insecure', 'insensible', 'insensitive', 'inseparable', 'inside',
              'insidious', 'insightful', 'insignificant', 'insincere', 'insipid', 'insistent', 'insolent',
              'inspirational', 'inspired', 'inspiring', 'instant', 'instantaneous', 'instinctive', 'instinctual',
              'institutional', 'instructive', 'instrumental', 'insubordinate', 'insufferable', 'insufficient',
              'insulted', 'insulting', 'insurable', 'insurmountable', 'intangible', 'integral', 'intellectual',
              'intelligent', 'intelligible', 'intended', 'intense', 'intensive', 'intentional', 'interactive',
              'interchangeable', 'interdepartmental', 'interdependent', 'interested', 'interesting', 'interior',
              'intermediate', 'intermittent', 'internal', 'international', 'interpersonal', 'interracial', 'intestinal',
              'intimate', 'intimidating', 'intolerable', 'intolerant', 'intravenous', 'intrepid', 'intricate',
              'intrigued', 'intriguing', 'intrinsic', 'introductory', 'introspective', 'introverted', 'intrusive',
              'intuitive', 'invalid', 'invaluable', 'invasive', 'inventive', 'invigorating', 'invincible', 'invisible',
              'invited', 'inviting', 'involuntary', 'involved', 'inward', 'irascible', 'irate', 'iridescent', 'irksome',
              'iron', 'iron-fisted', 'ironic', 'irrational', 'irreconcilable', 'irrefutable', 'irregular', 'irrelative',
              'irrelevant', 'irremovable', 'irreparable', 'irreplaceable', 'irrepressible', 'irresistible',
              'irresponsible', 'irretrievably', 'irreverent', 'irreversible', 'irrevocable', 'irritable', 'irritated',
              'irritating', 'isolated', 'itchy', 'its', 'itty-bitty', 'jabbering', 'jaded', 'jagged', 'jarring',
              'jaundiced', 'jazzy', 'jealous', 'jeering', 'jerky', 'jiggling', 'jittery', 'jobless', 'jocular', 'joint',
              'jolly', 'jovial', 'joyful', 'joyless', 'joyous', 'jubilant', 'judgmental', 'judicious', 'juicy',
              'jumbled', 'jumpy', 'junior', 'just', 'justifiable', 'juvenile', 'kaput', 'keen', 'key', 'kind',
              'kindhearted', 'kindly', 'kinesthetic', 'kingly', 'kitchen', 'knavish', 'knightly', 'knobbed', 'knobby',
              'knotty', 'knowable', 'knowing', 'knowledgeable', 'known', 'labored', 'laborious', 'lackadaisical',
              'lacking', 'lacy', 'lame', 'lamentable', 'languid', 'languishing', 'lanky', 'larcenous', 'large',
              'larger', 'largest', 'lascivious', 'last', 'lasting', 'late', 'latent', 'later', 'lateral', 'latest',
              'latter', 'laudable', 'laughable', 'laughing', 'lavish', 'lawful', 'lawless', 'lax', 'lazy', 'lead',
              'leading', 'lean', 'learnable', 'learned', 'leased', 'least', 'leather', 'leathery', 'lecherous',
              'leering', 'left', 'left-handed', 'legal', 'legendary', 'legible', 'legislative', 'legitimate', 'lengthy',
              'lenient', 'less', 'lesser', 'lesser-known', 'less-qualified', 'lethal', 'lethargic', 'level', 'liable',
              'libelous', 'liberal', 'licensed', 'life', 'lifeless', 'lifelike', 'lifelong', 'light', 'light-blue',
              'lighthearted', 'likable', 'likeable', 'likely', 'like-minded', 'lily-livered', 'limber', 'limited',
              'limitless', 'limp', 'limping', 'linear', 'lined', 'lingering', 'linguistic', 'liquid', 'listless',
              'literal', 'literary', 'literate', 'lithe', 'lithographic', 'litigious', 'little', 'livable', 'live',
              'lively', 'livid', 'living', 'loathsome', 'local', 'locatable', 'locked', 'lofty', 'logarithmic',
              'logical', 'logistic', 'lonely', 'long', 'longer', 'longest', 'longing', 'long-term', 'long-winded',
              'loose', 'lopsided', 'loquacious', 'lordly', 'lost', 'loud', 'lousy', 'loutish', 'lovable', 'loveable',
              'lovely', 'loving', 'low', 'low-calorie', 'low-carb', 'lower', 'low-fat', 'lowly', 'low-maintenance',
              'low-ranking', 'low-risk', 'loyal', 'lucent', 'lucid', 'lucky', 'lucrative', 'ludicrous', 'lukewarm',
              'lulling', 'luminescent', 'luminous', 'lumpy', 'lurid', 'luscious', 'lush', 'lustrous', 'luxurious',
              'lying', 'lyrical', 'macabre', 'Machiavellian', 'macho', 'mad', 'maddening', 'magenta', 'magic',
              'magical', 'magnanimous', 'magnetic', 'magnificent', 'maiden', 'main', 'maintainable', 'majestic',
              'major', 'makeable', 'makeshift', 'maladjusted', 'male', 'malevolent', 'malicious', 'malignant',
              'malleable', 'mammoth', 'manageable', 'managerial', 'mandatory', 'maneuverable', 'mangy', 'maniacal',
              'manic', 'manicured', 'manipulative', 'man-made', 'manual', 'many', 'marbled', 'marginal', 'marked',
              'marketable', 'married', 'marvelous', 'masked', 'massive', 'master', 'masterful', 'matchless', 'material',
              'materialistic', 'maternal', 'mathematical', 'matronly', 'matted', 'mature', 'maximum', 'meager', 'mean',
              'meandering', 'meaningful', 'meaningless', 'mean-spirited', 'measly', 'measurable', 'meat-eating',
              'meaty', 'mechanical', 'medical', 'medicinal', 'meditative', 'medium', 'medium-rare', 'meek',
              'melancholy', 'mellow', 'melodic', 'melodious', 'melodramatic', 'melted', 'memorable', 'menacing',
              'menial', 'mental', 'merciful', 'merciless', 'mercurial', 'mere', 'merry', 'messy', 'metabolic',
              'metallic', 'metaphoric', 'meteoric', 'meticulous', 'microscopic', 'microwaveable', 'middle',
              'middle-class', 'midweek', 'mighty', 'mild', 'militant', 'militaristic', 'military', 'milky', 'mincing',
              'mind-bending', 'mindful', 'mindless', 'mini', 'miniature', 'minimal', 'minimum', 'minor', 'minute',
              'miraculous', 'mirthful', 'miscellaneous', 'mischievous', 'miscreant', 'miserable', 'miserly',
              'misguided', 'misleading', 'mission', 'mistaken', 'mistrustful', 'mistrusting', 'misty', 'mixed',
              'mnemonic', 'moaning', 'mobile', 'mocking', 'moderate', 'modern', 'modest', 'modified', 'modular',
              'moist', 'moldy', 'momentary', 'momentous', 'monetary', 'money-grubbing', 'monopolistic', 'monosyllabic',
              'monotone', 'monotonous', 'monstrous', 'monumental', 'moody', 'moral', 'moralistic', 'morbid', 'mordant',
              'more', 'moronic', 'morose', 'mortal', 'mortified', 'most', 'mother', 'motherly', 'motionless',
              'motivated', 'motivating', 'motivational', 'motor', 'mountain', 'mountainous', 'mournful',
              'mouthwatering', 'movable', 'moved', 'moving', 'much', 'muddled', 'muddy', 'muffled', 'muggy',
              'multicultural', 'multifaceted', 'multipurpose', 'multitalented', 'mumbled', 'mundane', 'municipal',
              'murky', 'muscular', 'mushy', 'musical', 'musky', 'musty', 'mutative', 'mute', 'muted', 'mutinous',
              'muttering', 'mutual', 'my', 'myopic', 'mysterious', 'mystic', 'mystical', 'mystified', 'mystifying',
              'mythical', 'naive', 'nameless', 'narcissistic', 'narrow', 'narrow-minded', 'nasal', 'nasty', 'national',
              'native', 'natural', 'naughty', 'nauseating', 'nauseous', 'nautical', 'navigable', 'navy-blue', 'near',
              'nearby', 'nearest', 'nearsighted', 'neat', 'nebulous', 'necessary', 'needless', 'needy', 'nefarious',
              'negative', 'neglected', 'neglectful', 'negligent', 'negligible', 'negotiable', 'neighborly', 'neither',
              'nerve-racking', 'nervous', 'neurological', 'neurotic', 'neutral', 'new', 'newest', 'next', 'next-door',
              'nice', 'nifty', 'nightmarish', 'nimble', 'nine', 'ninth', 'nippy', 'no', 'noble', 'nocturnal',
              'noiseless', 'noisy', 'nominal', 'nonabrasive', 'nonaggressive', 'nonchalant', 'noncommittal',
              'noncompetitive', 'nonconsecutive', 'nondescript', 'nondestructive', 'nonexclusive', 'nonnegotiable',
              'nonproductive', 'nonrefundable', 'nonrenewable', 'nonresponsive', 'nonrestrictive', 'nonreturnable',
              'nonsensical', 'nonspecific', 'nonstop', 'nontransferable', 'nonverbal', 'nonviolent', 'normal', 'north',
              'northeast', 'northerly', 'northwest', 'nostalgic', 'nosy', 'notable', 'noticeable', 'notorious', 'novel',
              'noxious', 'null', 'numb', 'numberless', 'numbing', 'numerable', 'numeric', 'numerous', 'nutritional',
              'nutritious', 'nutty', 'oafish', 'obedient', 'obeisant', 'obese', 'objectionable', 'objective',
              'obligatory', 'obliging', 'oblique', 'oblivious', 'oblong', 'obnoxious', 'obscene', 'obscure',
              'observable', 'observant', 'obsessive', 'obsolete', 'obstinate', 'obstructive', 'obtainable', 'obtrusive',
              'obtuse', 'obvious', 'occasional', 'occupational', 'occupied', 'oceanic', 'odd', 'odd-looking',
              'odiferous', 'odious', 'odorless', 'odorous', 'offbeat', 'offensive', 'offhanded', 'official',
              'officious', 'oily', 'OK', 'okay', 'old', 'older', 'oldest', 'old-fashioned', 'ominous', 'omniscient',
              'omnivorous', 'one', 'one-hour', 'onerous', 'one-sided', 'only', 'opaque', 'open', 'opened', 'openhanded',
              'openhearted', 'opening', 'open-minded', 'operable', 'operatic', 'operational', 'operative',
              'opinionated', 'opportune', 'opportunistic', 'opposable', 'opposed', 'opposing', 'opposite', 'oppressive',
              'optimal', 'optimistic', 'optional', 'opulent', 'oral', 'orange', 'ordinary', 'organic', 'organizational',
              'original', 'ornamental', 'ornate', 'ornery', 'orphaned', 'orthopedic', 'ossified', 'ostentatious',
              'other', 'otherwise', 'our', 'outer', 'outermost', 'outgoing', 'outlandish', 'outraged', 'outrageous',
              'outside', 'outspoken', 'outstanding', 'outward', 'oval', 'overactive', 'overaggressive', 'overall',
              'overambitious', 'overassertive', 'overbearing', 'overcast', 'overcautious', 'overconfident',
              'overcritical', 'overcrowded', 'overemotional', 'overenthusiastic', 'overjoyed', 'overoptimistic',
              'overpowering', 'overpriced', 'overprotective', 'overqualified', 'overrated', 'oversensitive',
              'oversized', 'overt', 'overwhelmed', 'overwhelming', 'overworked', 'overwrought', 'overzealous', 'own',
              'oxymoronic', 'padded', 'painful', 'painless', 'painstaking', 'palatable', 'palatial', 'pale', 'pallid',
              'palpable', 'paltry', 'pampered', 'panicky', 'panoramic', 'paradoxical', 'parallel', 'paranormal',
              'parasitic', 'parched', 'pardonable', 'parental', 'parenthetic', 'parking', 'parsimonious', 'partial',
              'particular', 'partisan', 'part-time', 'party', 'passing', 'passionate', 'passive', 'past', 'pastoral',
              'patched', 'patchy', 'patented', 'paternal', 'paternalistic', 'pathetic', 'pathological', 'patient',
              'patriotic', 'patronizing', 'patterned', 'payable', 'peaceable', 'peaceful', 'peculiar', 'pedantic',
              'pedestrian', 'peerless', 'peeved', 'peevish', 'penetrable', 'penetrating', 'pensive', 'peppery',
              'perceivable', 'perceptible', 'perceptive', 'perceptual', 'peremptory', 'perennial', 'perfect',
              'perfumed', 'perilous', 'period', 'periodic', 'peripheral', 'perishable', 'perky', 'permanent',
              'permeable', 'permissible', 'permissive', 'pernicious', 'perpendicular', 'perpetual', 'perplexed',
              'perplexing', 'persevering', 'persistent', 'personable', 'personal', 'persuasive', 'pert', 'pertinent',
              'perturbed', 'perturbing', 'pervasive', 'perverse', 'pessimistic', 'petite', 'pettish', 'petty',
              'petulant', 'pharmaceutical', 'phenomenal', 'philanthropic', 'philosophical', 'phobic', 'phonemic',
              'phonetic', 'phosphorescent', 'photographic', 'physical', 'physiological', 'picturesque', 'piercing',
              'pigheaded', 'pink', 'pious', 'piquant', 'pitch-dark', 'pitch-perfect', 'piteous', 'pithy', 'pitiful',
              'pitiless', 'pivotal', 'placid', 'plaid', 'plain', 'plane', 'planned', 'plastic', 'platonic', 'plausible',
              'playful', 'pleading', 'pleasant', 'pleased', 'pleasing', 'pleasurable', 'plentiful', 'pliable',
              'plodding', 'plopping', 'plucky', 'plump', 'pluralistic', 'plus', 'plush', 'pneumatic', 'poetic',
              'poignant', 'pointless', 'poised', 'poisonous', 'polished', 'polite', 'political', 'polka-dotted',
              'polluted', 'polyunsaturated', 'pompous', 'ponderous', 'poor', 'poorer', 'poorest', 'popping', 'popular',
              'populous', 'porous', 'portable', 'portly', 'positive', 'possessive', 'possible', 'post', 'posthumous',
              'postoperative', 'potable', 'potent', 'potential', 'powdery', 'powerful', 'powerless', 'practical',
              'pragmatic', 'praiseworthy', 'precarious', 'precious', 'precipitous', 'precise', 'precocious',
              'preconceived', 'predicative', 'predictable', 'predisposed', 'predominant', 'preeminent', 'preemptive',
              'prefabricated', 'preferable', 'preferential', 'pregnant', 'prehistoric', 'prejudiced', 'prejudicial',
              'preliminary', 'premature', 'premeditated', 'premium', 'prenatal', 'preoccupied', 'preoperative',
              'preparative', 'prepared', 'preposterous', 'prescriptive', 'present', 'presentable', 'presidential',
              'pressing', 'pressurized', 'prestigious', 'presumable', 'presumptive', 'presumptuous', 'pretend',
              'pretentious', 'pretty', 'prevalent', 'preventable', 'preventative', 'preventive', 'previous',
              'priceless', 'pricey', 'prickly', 'prim', 'primary', 'primitive', 'primordial', 'princely', 'principal',
              'principled', 'prior', 'prissy', 'pristine', 'private', 'prize', 'prized', 'proactive', 'probabilistic',
              'probable', 'problematic', 'procedural', 'prodigious', 'productive', 'profane', 'professed',
              'professional', 'professorial', 'proficient', 'profitable', 'profound', 'profuse', 'programmable',
              'progressive', 'prohibitive', 'prolific', 'prominent', 'promised', 'promising', 'prompt', 'pronounceable',
              'pronounced', 'proof', 'proper', 'prophetic', 'proportional', 'proportionate', 'proportioned',
              'prospective', 'prosperous', 'protective', 'prototypical', 'proud', 'proverbial', 'provisional',
              'provocative', 'provoking', 'proximal', 'proximate', 'prudent', 'prudential', 'prying', 'psychedelic',
              'psychiatric', 'psychological', 'psychosomatic', 'psychotic', 'public', 'puckish', 'puffy', 'pugnacious',
              'pumped', 'punctual', 'pungent', 'punishable', 'punitive', 'puny', 'pure', 'purified', 'puritanical',
              'purple', 'purported', 'purposeful', 'purposeless', 'purring', 'pushy', 'pusillanimous', 'putrid',
              'puzzled', 'puzzling', 'pyrotechnic', 'quackish', 'quacky', 'quaint', 'qualified', 'qualitative',
              'quality', 'quantifiable', 'quantitative', 'quarrelsome', 'queasy', 'queenly', 'querulous',
              'questionable', 'quick', 'quick-acting', 'quick-drying', 'quickest', 'quick-minded', 'quick-paced',
              'quick-tempered', 'quick-thinking', 'quick-witted', 'quiet', 'quintessential', 'quirky', 'quivering',
              'quizzical', 'quotable', 'rabid', 'racial', 'racist', 'radiant', 'radical', 'radioactive', 'ragged',
              'raging', 'rainbow', 'rainy', 'rakish', 'rambling', 'rambunctious', 'rampageous', 'rampant', 'rancid',
              'rancorous', 'random', 'rank', 'rapid', 'rapid-fire', 'rapturous', 'rare', 'rascally', 'rash', 'rasping',
              'raspy', 'rational', 'ratty', 'ravenous', 'raving', 'ravishing', 'raw', 'razor-edged', 'reactive',
              'ready', 'real', 'realistic', 'reasonable', 'reassured', 'reassuring', 'rebel', 'rebellious', 'receding',
              'recent', 'receptive', 'recessive', 'rechargeable', 'reciprocal', 'reckless', 'reclusive', 'recognizable',
              'recognized', 'rectangular', 'rectifiable', 'recurrent', 'recyclable', 'red', 'red-blooded', 'reddish',
              'redeemable', 'redolent', 'redundant', 'referential', 'refillable', 'reflective', 'refractive',
              'refreshing', 'refundable', 'refurbished', 'refutable', 'regal', 'regional', 'regretful', 'regrettable',
              'regular', 'reigning', 'relatable', 'relative', 'relaxed', 'relaxing', 'relentless', 'relevant',
              'reliable', 'relieved', 'religious', 'reluctant', 'remaining', 'remarkable', 'remedial', 'reminiscent',
              'remorseful', 'remorseless', 'remote', 'removable', 'renegotiable', 'renewable', 'rented', 'repairable',
              'repaired', 'repeated', 'repentant', 'repetitious', 'repetitive', 'replaceable', 'replicable', 'reported',
              'reprehensible', 'representative', 'repressive', 'reproachful', 'reproductive', 'republican', 'repugnant',
              'repulsive', 'reputable', 'reputed', 'rescued', 'resealable', 'resentful', 'reserved', 'resident',
              'residential', 'residual', 'resilient', 'resolute', 'resolvable', 'resonant', 'resounding', 'resourceful',
              'respectable', 'respectful', 'respective', 'responsible', 'responsive', 'rested', 'restful', 'restless',
              'restored', 'restrained', 'restrictive', 'retired', 'retroactive', 'retrogressive', 'retrospective',
              'reusable', 'revamped', 'revealing', 'revengeful', 'reverent', 'reverential', 'reverse', 'reversible',
              'reviewable', 'reviled', 'revisable', 'revised', 'revocable', 'revolting', 'revolutionary', 'rewarding',
              'rhetorical', 'rhythmic', 'rich', 'richer', 'richest', 'ridiculing', 'ridiculous', 'right', 'righteous',
              'rightful', 'right-handed', 'rigid', 'rigorous', 'ringing', 'riotous', 'ripe', 'rippling', 'risky',
              'ritualistic', 'ritzy', 'riveting', 'roaring', 'roasted', 'robotic', 'robust', 'rocketing', 'roguish',
              'romantic', 'roomy', 'rosy', 'rotating', 'rotten', 'rotting', 'rotund', 'rough', 'round', 'roundtable',
              'rousing', 'routine', 'rowdy', 'royal', 'ruddy', 'rude', 'rudimentary', 'rueful', 'rugged', 'ruined',
              'ruinous', 'rumbling', 'rumpled', 'ruptured', 'rural', 'rusted', 'rustic', 'rustling', 'rusty',
              'ruthless', 'rutted', 'saccharin', 'sacred', 'sacrificial', 'sacrilegious', 'sad', 'saddened', 'safe',
              'saintly', 'salacious', 'salient', 'salt', 'salted', 'salty', 'salvageable', 'salvaged', 'same',
              'sanctimonious', 'sandy', 'sane', 'sanguine', 'sanitary', 'sappy', 'sarcastic', 'sardonic', 'sassy',
              'satin', 'satiny', 'satiric', 'satirical', 'satisfactory', 'satisfied', 'satisfying', 'saucy', 'savage',
              'savory', 'savvy', 'scalding', 'scaly', 'scandalous', 'scant', 'scanty', 'scarce', 'scared', 'scarred',
              'scary', 'scathing', 'scattered', 'scenic', 'scented', 'scheduled', 'schematic', 'scholarly',
              'scholastic', 'scientific', 'scintillating', 'scorching', 'scornful', 'scrabbled', 'scraggly', 'scrappy',
              'scratched', 'scratchy', 'scrawny', 'screaming', 'screeching', 'scribbled', 'scriptural', 'scruffy',
              'scrumptious', 'scrupulous', 'sculpted', 'sculptural', 'scummy', 'sea', 'sealed', 'seamless', 'searching',
              'searing', 'seasick', 'seasonable', 'seasonal', 'secluded', 'second', 'secondary', 'second-hand',
              'secret', 'secretive', 'secular', 'secure', 'secured', 'sedate', 'seditious', 'seductive', 'seedy',
              'seeming', 'seemly', 'seething', 'seismic', 'select', 'selected', 'selective', 'self-absorbed',
              'self-aggrandizing', 'self-assured', 'self-centered', 'self-confident', 'self-directed',
              'self-disciplined', 'self-effacing', 'self-indulgent', 'self-interested', 'selfish', 'selfless',
              'self-reliant', 'self-respect', 'self-satisfied', 'sellable', 'semiconscious', 'semiofficial',
              'semiprecious', 'semiprofessional', 'senior', 'sensational', 'senseless', 'sensible', 'sensitive',
              'sensual', 'sensuous', 'sentimental', 'separate', 'sequential', 'serendipitous', 'serene', 'serial',
              'serious', 'serrated', 'serviceable', 'seven', 'seventh', 'several', 'severe', 'shabbiest', 'shabby',
              'shaded', 'shadowed', 'shadowy', 'shady', 'shaggy', 'shaky', 'shallow', 'shamefaced', 'shameful',
              'shameless', 'shapeless', 'shapely', 'sharp', 'sharpened', 'shattered', 'shattering', 'sheepish', 'sheer',
              'sheltered', 'shifty', 'shimmering', 'shining', 'shiny', 'shivering', 'shivery', 'shocked', 'shocking',
              'shoddy', 'short', 'short-lived', 'shortsighted', 'short-tempered', 'short-term', 'showy', 'shrewd',
              'shrieking', 'shrill', 'shut', 'shy', 'sick', 'sickened', 'sickening', 'sickly', 'side-splitting',
              'signed', 'significant', 'silent', 'silky', 'silly', 'silver', 'silver-tongued', 'simian', 'similar',
              'simple', 'simpleminded', 'simplified', 'simplistic', 'simultaneous', 'sincere', 'sinful', 'single',
              'single-minded', 'singular', 'sinister', 'sinuous', 'sisterly', 'six', 'sixth', 'sizable', 'sizzling',
              'skeptical', 'sketchy', 'skilled', 'skillful', 'skimpy', 'skin-deep', 'skinny', 'skittish', 'sky-blue',
              'slanderous', 'slanted', 'slanting', 'sleek', 'sleeping', 'sleepless', 'sleepy', 'slender', 'slick',
              'slight', 'slim', 'slimy', 'slippery', 'sloped', 'sloping', 'sloppy', 'slothful', 'slow', 'slow-moving',
              'sluggish', 'slushy', 'sly', 'small', 'smaller', 'smallest', 'small-minded', 'small-scale', 'small-time',
              'small-town', 'smarmy', 'smart', 'smarter', 'smartest', 'smashing', 'smeared', 'smelly', 'smiling',
              'smoggy', 'smoked', 'smoky', 'smooth', 'smothering', 'smudged', 'smug', 'snapping', 'snappish', 'snappy',
              'snarling', 'sneaky', 'snide', 'snippy', 'snobbish', 'snoopy', 'snooty', 'snoring', 'snotty',
              'snow-white', 'snug', 'snuggly', 'soaked', 'soaking', 'soaking', 'soaring', 'sober', 'sociable', 'social',
              'socialist', 'sociological', 'soft', 'softhearted', 'soggy', 'solar', 'soldierly', 'sole', 'solemn',
              'solicitous', 'solid', 'solitary', 'somatic', 'somber', 'some', 'sonic', 'sonly', 'soothed', 'soothing',
              'sophisticated', 'sordid', 'sore', 'sorrowful', 'sorry', 'soulful', 'soulless', 'soundless', 'sour',
              'south', 'southeasterly', 'southern', 'southwestern', 'spacious', 'spare', 'sparing', 'sparkling',
              'sparkly', 'sparse', 'spasmodic', 'spastic', 'spatial', 'spattered', 'special', 'specialist',
              'specialized', 'specific', 'speckled', 'spectacular', 'spectral', 'speculative', 'speechless', 'speedy',
              'spellbinding', 'spendthrift', 'spherical', 'spicy', 'spiffy', 'spiky', 'spinal', 'spineless', 'spiral',
              'spiraled', 'spirited', 'spiritless', 'spiritual', 'spiteful', 'splashing', 'splashy', 'splattered',
              'splendid', 'splintered', 'spoiled', 'spoken', 'spongy', 'spontaneous', 'spooky', 'sporadic', 'sporting',
              'sportsmanly', 'spotless', 'spotted', 'spotty', 'springy', 'sprite', 'spry', 'spurious', 'squalid',
              'squandered', 'square', 'squashed', 'squashy', 'squatting', 'squawking', 'squealing', 'squeamish',
              'squeezable', 'squiggly', 'squirming', 'squirrelly', 'stable', 'stackable', 'stacked', 'staggering',
              'stagnant', 'stained', 'stale', 'stanch', 'standard', 'standing', 'standoffish', 'starched',
              'star-crossed', 'stark', 'startled', 'startling', 'starving', 'stately', 'static', 'statistical',
              'statuesque', 'status', 'statutory', 'staunch', 'steadfast', 'steady', 'stealth', 'steaming', 'steamy',
              'steel', 'steely', 'steep', 'stereophonic', 'stereotyped', 'stereotypical', 'sterile', 'stern', 'sticky',
              'stiff', 'stifled', 'stifling', 'stigmatic', 'still', 'stilled', 'stilted', 'stimulating', 'stinging',
              'stingy', 'stinking', 'stinky', 'stirring', 'stock', 'stodgy', 'stoic', 'stony', 'stormy', 'stout',
              'straggly', 'straight', 'straightforward', 'stranded', 'strange', 'strategic', 'streaked', 'street',
              'strenuous', 'stressful', 'stretchy', 'strict', 'strident', 'striking', 'stringent', 'striped', 'strong',
              'stronger', 'strongest', 'structural', 'stubborn', 'stubby', 'stuck-up', 'studied', 'studious', 'stuffed',
              'stuffy', 'stumbling', 'stunned', 'stunning', 'stupendous', 'sturdy', 'stuttering', 'stylish',
              'stylistic', 'suave', 'subconscious', 'subdued', 'subject', 'subjective', 'sublime', 'subliminal',
              'submissive', 'subordinate', 'subsequent', 'subservient', 'substantial', 'substantiated', 'substitute',
              'subterranean', 'subtitled', 'subtle', 'subversive', 'successful', 'successive', 'succinct', 'succulent',
              'such', 'sudden', 'suffering', 'sufficient', 'sugary', 'suggestive', 'suitable', 'sulky', 'sullen',
              'sumptuous', 'sunny', 'super', 'superabundant', 'superb', 'supercilious', 'superficial', 'superhuman',
              'superior', 'superlative', 'supernatural', 'supersensitive', 'supersonic', 'superstitious', 'supple',
              'supportive', 'supposed', 'suppressive', 'supreme', 'sure', 'sure-footed', 'surgical', 'surly',
              'surmountable', 'surprised', 'surprising', 'surrealistic', 'survivable', 'susceptible', 'suspected',
              'suspicious', 'sustainable', 'swaggering', 'swanky', 'swaying', 'sweaty', 'sweeping', 'sweet',
              'sweltering', 'swift', 'swimming', 'swinish', 'swishing', 'swollen', 'swooping', 'syllabic',
              'syllogistic', 'symbiotic', 'symbolic', 'symmetrical', 'sympathetic', 'symptomatic', 'synergistic',
              'synonymous', 'syntactic', 'synthetic', 'systematic', 'taboo', 'tacit', 'tacky', 'tactful', 'tactical',
              'tactless', 'tactual', 'tainted', 'take-charge', 'talented', 'talkative', 'tall', 'taller', 'tallest',
              'tame', 'tamed', 'tan', 'tangential', 'tangible', 'tangled', 'tangy', 'tanned', 'tantalizing', 'tapered',
              'tardy', 'targeted', 'tarnished', 'tart', 'tasteful', 'tasteless', 'tasty', 'tattered', 'taunting',
              'taut', 'taxing', 'teachable', 'tearful', 'tearing', 'teasing', 'technical', 'technological', 'tectonic',
              'tedious', 'teenage', 'teensy', 'teeny', 'teeny-tiny', 'telegraphic', 'telekinetic', 'telepathic',
              'telephonic', 'telescopic', 'telling', 'temperamental', 'temperate', 'tempestuous', 'temporary',
              'tempted', 'tempting', 'ten', 'tenable', 'tenacious', 'tender', 'tenderhearted', 'ten-minute', 'tense',
              'tentative', 'tenth', 'tenuous', 'tepid', 'terminal', 'terrestrial', 'terrible', 'terrific', 'terrified',
              'terrifying', 'territorial', 'terse', 'tested', 'testy', 'tetchy', 'textual', 'textural', 'thankful',
              'thankless', 'that', 'the', 'theatrical', 'their', 'thematic', 'theological', 'theoretical',
              'therapeutic', 'thermal', 'these', 'thick', 'thievish', 'thin', 'thinkable', 'third', 'thirsty', 'this',
              'thorny', 'thorough', 'those', 'thoughtful', 'thoughtless', 'thrashed', 'threatened', 'threatening',
              'three', 'thriftless', 'thrifty', 'thrilled', 'thrilling', 'throbbing', 'thumping', 'thundering',
              'thunderous', 'ticking', 'tickling', 'ticklish', 'tidal', 'tidy', 'tight', 'tightfisted', 'time',
              'timeless', 'timely', 'timid', 'timorous', 'tiny', 'tipsy', 'tired', 'tireless', 'tiresome', 'tiring',
              'tolerable', 'tolerant', 'tonal', 'tone-deaf', 'toneless', 'toothsome', 'toothy', 'top', 'topical',
              'topographical', 'tormented', 'torpid', 'torrential', 'torrid', 'torturous', 'total', 'touched',
              'touching', 'touchy', 'tough', 'towering', 'toxic', 'traditional', 'tragic', 'trainable', 'trained',
              'training', 'traitorous', 'tranquil', 'transcendent', 'transcendental', 'transformational',
              'transformative', 'transformed', 'transient', 'transitional', 'transitory', 'translucent', 'transparent',
              'transplanted', 'trapped', 'trashed', 'trashy', 'traumatic', 'treacherous', 'treasonable', 'treasonous',
              'treasured', 'treatable', 'tremendous', 'tremulous', 'trenchant', 'trendy', 'triangular', 'tribal',
              'trick', 'tricky', 'trim', 'tripping', 'trite', 'triumphant', 'trivial', 'tropical', 'troubled',
              'troublesome', 'troubling', 'truculent', 'true', 'trusted', 'trustful', 'trusting', 'trustworthy',
              'trusty', 'truthful', 'trying', 'tumultuous', 'tuneful', 'tuneless', 'turbulent', 'twinkling', 'twinkly',
              'twisted', 'twitchy', 'two', 'typical', 'tyrannical', 'tyrannous', 'ubiquitous', 'ugly', 'ultimate',
              'ultraconservative', 'ultrasensitive', 'ultrasonic', 'ultraviolet', 'unabashed', 'unabated', 'unable',
              'unacceptable', 'unaccompanied', 'unaccountable', 'unaccustomed', 'unacknowledged', 'unadorned',
              'unadulterated', 'unadventurous', 'unadvised', 'unaffected', 'unaffordable', 'unafraid', 'unaggressive',
              'unaided', 'unalienable', 'unalterable', 'unaltered', 'unambiguous', 'unanimous', 'unannounced',
              'unanswerable', 'unanticipated', 'unapologetic', 'unappealing', 'unappetizing', 'unappreciative',
              'unapproachable', 'unashamed', 'unassailable', 'unassertive', 'unassisted', 'unattached', 'unattainable',
              'unattractive', 'unauthorized', 'unavailable', 'unavailing', 'unavoidable', 'unbalanced', 'unbearable',
              'unbeatable', 'unbeaten', 'unbecoming', 'unbelievable', 'unbelieving', 'unbendable', 'unbending',
              'unbiased', 'unblemished', 'unblinking', 'unblushing', 'unbounded', 'unbreakable', 'unbridled', 'uncanny',
              'uncaring', 'unceasing', 'unceremonious', 'uncertain', 'unchangeable', 'unchanging', 'uncharacteristic',
              'uncharitable', 'uncharted', 'uncivil', 'uncivilized', 'unclassified', 'unclean', 'uncluttered',
              'uncomely', 'uncomfortable', 'uncommitted', 'uncommon', 'uncommunicative', 'uncomplaining',
              'uncomprehending', 'uncompromising', 'unconcerned', 'unconditional', 'unconfirmed', 'unconquerable',
              'unconscionable', 'unconscious', 'unconstitutional', 'unconstrained', 'unconstructive', 'uncontainable',
              'uncontrollable', 'unconventional', 'unconvinced', 'unconvincing', 'uncooked', 'uncooperative',
              'uncoordinated', 'uncouth', 'uncovered', 'uncreative', 'uncritical', 'undamaged', 'undated', 'undaunted',
              'undeclared', 'undefeated', 'undefined', 'undemocratic', 'undeniable', 'undependable', 'underdeveloped',
              'underfunded', 'underhanded', 'underprivileged', 'understandable', 'understanding', 'understated',
              'understood', 'undeserved', 'undesirable', 'undetected', 'undeterred', 'undeveloped', 'undeviating',
              'undifferentiated', 'undignified', 'undiminished', 'undiplomatic', 'undisciplined', 'undiscovered',
              'undisguised', 'undisputed', 'undistinguished', 'undivided', 'undoubted', 'unearthly', 'uneasy',
              'uneducated', 'unemotional', 'unemployed', 'unencumbered', 'unending', 'unendurable', 'unenforceable',
              'unenthusiastic', 'unenviable', 'unequal', 'unequaled', 'unequivocal', 'unerring', 'uneven', 'uneventful',
              'unexceptional', 'unexcited', 'unexpected', 'unexplainable', 'unexplored', 'unexpressive', 'unfailing',
              'unfair', 'unfaithful', 'unfaltering', 'unfamiliar', 'unfashionable', 'unfathomable', 'unfavorable',
              'unfeeling', 'unfettered', 'unfilled', 'unflagging', 'unflappable', 'unflattering', 'unflinching',
              'unfocused', 'unforeseeable', 'unforgettable', 'unforgivable', 'unforgiving', 'unfortunate', 'unfriendly',
              'unfulfilled', 'ungallant', 'ungenerous', 'ungentlemanly', 'unglamorous', 'ungraceful', 'ungracious',
              'ungrateful', 'unguarded', 'unhandsome', 'unhappy', 'unharmed', 'unhealthy', 'unheated', 'unheeded',
              'unhelpful', 'unhesitating', 'unhurried', 'uniform', 'unilateral', 'unimaginable', 'unimaginative',
              'unimpeachable', 'unimpeded', 'unimpressive', 'unincorporated', 'uninformed', 'uninhabitable',
              'uninhibited', 'uninitiated', 'uninjured', 'uninspired', 'uninsurable', 'unintelligent', 'unintelligible',
              'unintended', 'unintentional', 'uninterested', 'uninterrupted', 'uninvited', 'unique', 'united',
              'universal', 'unjust', 'unjustifiable', 'unkempt', 'unkind', 'unknowing', 'unknown', 'unlawful',
              'unlicensed', 'unlikable', 'unlikely', 'unlivable', 'unloved', 'unlucky', 'unmanageable', 'unmanly',
              'unmanned', 'unmarketable', 'unmasked', 'unmatched', 'unmemorable', 'unmentionable', 'unmerciful',
              'unmistakable', 'unmitigated', 'unmodified', 'unmotivated', 'unnatural', 'unnecessary', 'unnerved',
              'unnerving', 'unnoticeable', 'unobserved', 'unobtainable', 'unobtrusive', 'unofficial', 'unopened',
              'unopposed', 'unorthodox', 'unostentatious', 'unpalatable', 'unpardonable', 'unpersuasive', 'unperturbed',
              'unplanned', 'unpleasant', 'unprecedented', 'unpredictable', 'unpretentious', 'unprincipled',
              'unproductive', 'unprofessional', 'unprofitable', 'unpromising', 'unpronounceable', 'unprovoked',
              'unqualified', 'unquantifiable', 'unquenchable', 'unquestionable', 'unquestioned', 'unquestioning',
              'unraveled', 'unreachable', 'unreadable', 'unrealistic', 'unrealized', 'unreasonable', 'unreceptive',
              'unrecognizable', 'unrecognized', 'unredeemable', 'unregulated', 'unrelenting', 'unreliable',
              'unremarkable', 'unremitting', 'unrepentant', 'unrepresentative', 'unrepresented', 'unreserved',
              'unrespectable', 'unresponsive', 'unrestrained', 'unripe', 'unrivaled', 'unromantic', 'unruffled',
              'unruly', 'unsafe', 'unsalvageable', 'unsatisfactory', 'unsatisfied', 'unscheduled', 'unscholarly',
              'unscientific', 'unscrupulous', 'unseasonable', 'unseemly', 'unselfish', 'unsettled', 'unsettling',
              'unshakable', 'unshapely', 'unsightly', 'unsigned', 'unsinkable', 'unskilled', 'unsociable',
              'unsolicited', 'unsolvable', 'unsolved', 'unsophisticated', 'unsound', 'unsparing', 'unspeakable',
              'unspoiled', 'unstable', 'unstated', 'unsteady', 'unstoppable', 'unstressed', 'unstructured',
              'unsubstantial', 'unsubstantiated', 'unsuccessful', 'unsuitable', 'unsuited', 'unsupervised',
              'unsupported', 'unsure', 'unsurpassable', 'unsurpassed', 'unsurprising', 'unsuspected', 'unsuspecting',
              'unsustainable', 'unsympathetic', 'unsystematic', 'untainted', 'untamable', 'untamed', 'untapped',
              'untenable', 'untested', 'unthinkable', 'unthinking', 'untidy', 'untimely', 'untitled', 'untouchable',
              'untraditional', 'untrained', 'untried', 'untroubled', 'untrustworthy', 'untruthful', 'unused', 'unusual',
              'unverified', 'unwary', 'unwashed', 'unwatchable', 'unwavering', 'unwholesome', 'unwieldy', 'unwilling',
              'unwise', 'unwitting', 'unworkable', 'unworldly', 'unworthy', 'unwritten', 'unyielding', 'upbeat',
              'upmost', 'upper', 'uppity', 'upright', 'uproarious', 'upset', 'upsetting', 'upstairs', 'uptight',
              'up-to-date', 'up-to-the-minute', 'upward', 'urbane', 'urgent', 'usable', 'used', 'useful', 'useless',
              'usual', 'utilitarian', 'utopian', 'utter', 'uttermost', 'vacant', 'vacillating', 'vacuous', 'vagabond',
              'vagrant', 'vague', 'vain', 'valiant', 'valid', 'valorous', 'valuable', 'vanishing', 'vapid', 'vaporous',
              'variable', 'varied', 'various', 'varying', 'vast', 'vegetable', 'vegetarian', 'vegetative', 'vehement',
              'velvety', 'venal', 'venerable', 'vengeful', 'venomous', 'venturesome', 'venturous', 'veracious',
              'verbal', 'verbose', 'verdant', 'verifiable', 'verified', 'veritable', 'vernacular', 'versatile',
              'versed', 'vertical', 'very', 'vexed', 'vexing', 'viable', 'vibrant', 'vibrating', 'vicarious', 'vicious',
              'victorious', 'vigilant', 'vigorous', 'vile', 'villainous', 'vindictive', 'vinegary', 'violent', 'violet',
              'viperous', 'viral', 'virtual', 'virtuous', 'virulent', 'visceral', 'viscous', 'visible', 'visionary',
              'visual', 'vital', 'vitriolic', 'vivacious', 'vivid', 'vocal', 'vocational', 'voiceless', 'volatile',
              'volcanic', 'voluminous', 'voluntary', 'voluptuous', 'voracious', 'vulgar', 'vulnerable', 'wacky',
              'wailing', 'waiting', 'wakeful', 'wandering', 'wanting', 'wanton', 'warlike', 'warm', 'warmest',
              'warning', 'warring', 'wary', 'waspish', 'waste', 'wasted', 'wasteful', 'watchful', 'waterlogged',
              'waterproof', 'watertight', 'watery', 'wavering', 'wax', 'waxen', 'weak', 'weakened', 'weak-willed',
              'wealthy', 'wearisome', 'weary', 'wee', 'weedy', 'week-long', 'weekly', 'weightless', 'weighty', 'weird',
              'welcoming', 'well', 'well-adjusted', 'well-argued', 'well-aware', 'well-balanced', 'well-behaved',
              'well-built', 'well-conceived', 'well-considered', 'well-crafted', 'well-deserved', 'well-developed',
              'well-done', 'well-dressed', 'well-educated', 'well-equipped', 'well-established', 'well-founded',
              'well-groomed', 'well-heeled', 'well-honed', 'well-informed', 'well-intentioned', 'well-kempt',
              'well-known', 'well-liked', 'well-lit', 'well-made', 'well-maintained', 'well-mannered', 'well-meaning',
              'well-off', 'well-placed', 'well-planned', 'well-prepared', 'well-qualified', 'well-read',
              'well-received', 'well-rounded', 'well-spoken', 'well-suited', 'well-thought-of', 'well-thought-out',
              'well-to-do', 'well-traveled', 'well-used', 'well-versed', 'well-worn', 'well-written', 'west', 'western',
              'wet', 'what', 'wheezing', 'which', 'whimpering', 'whimsical', 'whining', 'whispering', 'whistling',
              'white', 'whole', 'wholehearted', 'wholesale', 'wholesome', 'whooping', 'whopping', 'whose', 'wicked',
              'wide', 'wide-eyed', 'wide-ranging', 'widespread', 'wiggly', 'wild', 'willful', 'willing', 'wily',
              'windy', 'winning', 'winsome', 'winter', 'wintery', 'wiry', 'wise', 'wishful', 'wispy', 'wistful',
              'withering', 'witless', 'witty', 'wizardly', 'wobbly', 'woeful', 'wolfish', 'wonderful', 'wondrous',
              'wonted', 'wood', 'wooden', 'wooing', 'wool', 'woolen', 'woozy', 'wordless', 'wordy', 'work', 'workable',
              'working', 'work-oriented', 'worldly', 'worn', 'worn', 'worn', 'worried', 'worrisome', 'worrying',
              'worse', 'worshipful', 'worst', 'worth', 'worthless', 'worthwhile', 'worthy', 'wounding', 'wrathful',
              'wrenching', 'wretched', 'wriggling', 'wriggly', 'wrinkled', 'wrinkly', 'written', 'wrong', 'wrongful',
              'wry', 'yawning', 'yearly', 'yearning', 'yellow', 'yelping', 'yielding', 'young', 'younger', 'youngest',
              'youthful', 'yummy', 'zany', 'zealous', 'zestful', 'zesty', 'zippy', 'zonked', 'zoological']
